# Generated by Django 4.1.5 on 2023-02-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeradvice',
            name='created_at',
        ),
    ]
